### ISSUE TITLE
How to handle updates to newer go releases

### ISSUE THREAD

**Issue by jonBoone** [Comcast/Buildenv-Tool#22]
In anticipation of a new Mac OS machine, I looked at installing this tool from scratch.  Prior to attempting to build the tool, I installed go using Homebrew.  The latest version of `brew install go` installs go.1.16, which was unable to properly compile the various combinations of GOOS and GOARCH the project expects, beginning with `darwin/386`.

I did manage to get the tool built by installing go.1.13 via `brew install go@1.13` (which is the version of go that the `go.mod` file in the master branch was created with).  Since go 1.16 was already installed, go 1.13 was not linked into /usr/local/ and requires a special path setting to enable its use.  With this, I was able to build the complete set of tools correctly.

Since new adopters (as well as, potentially, older adopters who are updating via source) _*will likely not have*_ go 1.13 installed, but go 1.16 or later, what is the project's approach to handling this situation?

**Comment by petershrom** [comment]
We have updated and this should be resolved now.  Thanks!
