### ISSUE TITLE
Forbidden Errors from Vault if No Kv2 Mount Exists

### ISSUE THREAD

**Issue by reskin89** [Comcast/Buildenv-Tool#35]
It seems buildenv may try to read a kv2 mount on start, even if one does not exist, which results in a 403 from vault.

Using an approle that only has access to paths `secret/` that is not part of a kv2 mount, and variables.yml has no kv2 secrets in it, I get:

```
Failure reading data: secret error: failure reading secret mounts: 403: 1 error occurred:
	* permission denied
```

with debug enabled I see "KVSecrets": null.

I downgraded to a previous version of buildenv that does not have kv2 functionality and the errors dissipated.

**Comment by lewg** [comment]
I believe this is resolved now with the changes around kv2 and auto-detection.
